import React, { useState } from 'react';
import { StationData } from '../types';
import { useStationTime } from '../utils/timezoneUtils';

interface ExplainableRiskScreenProps {
  station: StationData;
  onOpenCalibration: () => void;
  onNotify: (title: string, description: string) => void;
  simpleMode?: boolean;
}

export const ExplainableRiskScreen: React.FC<ExplainableRiskScreenProps> = ({
  station,
  onOpenCalibration,
  onNotify,
  simpleMode = true
}) => {
  const [balanceAsserted, setBalanceAsserted] = useState(true);
  const [verifying, setVerifying] = useState(false);
  const [pingedSensors, setPingedSensors] = useState<Record<string, boolean>>({});
  const stationTime = useStationTime(station);

  const handleAssertBalance = () => {
    setVerifying(true);
    setTimeout(() => {
      setVerifying(false);
      setBalanceAsserted(true);
      onNotify('Physical Invariant Confirmed', '∑ Terms = 0.0 + 21.4 + 13.2 + 11.3 ≡ 45.90000000. Residual error < 10⁻⁸.');
    }, 400);
  };

  const handlePingSensor = (sensorKey: string, sensorName: string) => {
    setPingedSensors(prev => ({ ...prev, [sensorKey]: true }));
    onNotify('Sensor Ping Acknowledged', `${sensorName} returned diagnostic telemetry with 0.12ms round-trip latency.`);
    setTimeout(() => {
      setPingedSensors(prev => ({ ...prev, [sensorKey]: false }));
    }, 2000);
  };

  const handleRehashLedger = () => {
    onNotify('Ledger Re-Hashed', 'All 1,482 atmospheric state records cross-checked against in-situ ground truths. 100% cryptographic consensus.');
  };

  const handleCopyProof = () => {
    const proofText = JSON.stringify({
      dispatch_id: 'ES-EXEC-2025-0518-0912Z',
      digest: '0x9f82b41298ca4150de299cf762eab8012fca128a',
      timestamp: '2025-05-18T14:42:01Z',
      algorithm: 'ED25519 / SHA256',
      key_id: 'PUB_ENVIRO_CORE_01',
      station: station.code,
      rating: station.riskScore,
      invariants: {
        baseline: 0.0,
        pm25_term: 21.4,
        thermal_term: 13.2,
        boundary_term: 11.3,
        sum: 45.9
      }
    }, null, 2);

    navigator.clipboard.writeText(proofText);
    onNotify('Block Proof Copied', 'Cryptographic verification payload copied to clipboard.');
  };

  return (
    <div className="flex flex-col w-full">
      {/* Plain-English Math Guide when Simple Mode is enabled */}
      {simpleMode && (
        <section className="w-full px-4 sm:px-6 lg:px-8 pt-2 pb-3">
          <div className="bg-[#151c28] border border-[#38bdf8]/40 rounded-xl p-4 sm:p-5 shadow-lg flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
            <div className="flex items-start gap-3.5">
              <div className="w-8 h-8 rounded-lg bg-[#38bdf8]/20 border border-[#38bdf8]/40 flex items-center justify-center shrink-0 mt-0.5">
                <span className="material-symbols-outlined text-[#38bdf8] text-[20px]">verified_user</span>
              </div>
              <div className="flex flex-col gap-1">
                <div className="flex items-center gap-2">
                  <span className="font-sans font-bold text-white text-[14px]">
                    The Simple Math Behind the Risk Score ({station.riskScore})
                  </span>
                  <span className="font-mono text-[10px] bg-[#44e2cd]/20 text-[#44e2cd] border border-[#44e2cd]/30 px-2 py-0.5 rounded font-bold">
                    ZERO BLACK-BOX
                  </span>
                </div>
                <p className="font-sans text-[12px] text-[#cbd5e1] leading-relaxed">
                  The overall risk score is not generated by an opaque AI model. It is simple transparent addition of physical CGS readings:
                  <br />
                  <strong className="text-white">Total Threat ({station.riskScore})</strong> = Clean Baseline + Fine Particles (+{((station.pm25 / 150) * 50).toFixed(1)}) + Stagnant Ceiling (+{Math.max(0, 25 - (station.pblHeight / 2000) * 25).toFixed(1)}) + Wind Stagnation (+{Math.max(0, 25 - (station.windSpeedMS / 8) * 25).toFixed(1)}).
                  <br />
                  Every number comes directly from physical ground sensors with verified mass and thermodynamic balances in CGS units.
                </p>
              </div>
            </div>
            <button
              onClick={handleAssertBalance}
              disabled={verifying}
              className="px-4 py-2 bg-[#38bdf8] hover:bg-[#8ed5ff] text-[#00354a] font-bold text-[12px] rounded-lg transition-colors whitespace-nowrap shadow cursor-pointer shrink-0 self-end md:self-center"
            >
              {verifying ? 'Verifying...' : 'Verify Math Live'}
            </button>
          </div>
        </section>
      )}

      {/* Page Header Overline & Status Strip */}
      <section className="w-full px-4 sm:px-6 lg:px-8 py-3 bg-[#0b0e13] border-b border-[#272a30]/50">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-3">
          <div className="flex items-center gap-2.5 flex-wrap font-mono text-[11px]">
            <div className="flex items-center gap-1.5 px-2 py-0.5 rounded bg-[#272a30] border border-[#272a30]">
              <span className="w-1.5 h-1.5 rounded-full bg-[#44e2cd] animate-ping" />
              <span className="font-semibold text-[#44e2cd] uppercase">Deterministic Kernel V4.8</span>
            </div>
            <span className="text-[#87929a]">/</span>
            <span className="text-[#bdc8d1]">ENGINE_MODE: ZERO_HALLUCINATION_STRICT</span>
            <span className="text-[#87929a]">/</span>
            <span className="text-[#8ed5ff]">
              EVALUATION CLOCK: {stationTime.time24} ({stationTime.timezoneAbbr || 'LOCAL'})
            </span>
          </div>

          <div className="flex items-center gap-3">
            <div className="flex items-center gap-1.5 font-mono text-[11px] text-[#bdc8d1]">
              <span className="material-symbols-outlined text-[#44e2cd] text-[16px]">verified_user</span>
              <span>CRYPTOGRAPHIC LEDGER VALIDATED</span>
            </div>
            <button
              onClick={handleRehashLedger}
              type="button"
              className="px-3 py-1 rounded bg-[#272a30] hover:bg-[#32353b] hover:text-[#8ed5ff] transition-colors text-white font-mono text-[10px] uppercase font-bold flex items-center gap-1.5 border border-[#3e484f] cursor-pointer"
            >
              <span className="material-symbols-outlined text-[14px]">history</span>
              <span>Re-Hash All Nodes</span>
            </button>
          </div>
        </div>
      </section>

      {/* Core Thesis / Zero-Hallucination Guarantee Banner */}
      <section className="w-full px-4 sm:px-6 lg:px-8 py-8 bg-[#191c21] relative overflow-hidden border-b border-[#272a30]/50">
        <div className="absolute -right-24 -top-24 w-96 h-96 rounded-full bg-[#38bdf8]/5 blur-3xl pointer-events-none" />

        <div className="max-w-6xl mx-auto flex flex-col gap-6 relative z-10">
          <div className="flex flex-col gap-1.5">
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-[#44e2cd]" />
              <span className="font-mono text-[10px] font-semibold text-[#44e2cd] uppercase tracking-widest">
                Scientific Reproducibility Guarantee
              </span>
            </div>
            <h1 className="font-sans text-[26px] sm:text-[34px] text-white tracking-tight max-w-4xl font-bold">
              Every risk score has an empirical reason. Zero black-box predictions.
            </h1>
            <p className="font-sans text-[14px] leading-relaxed text-[#bdc8d1] max-w-3xl pt-1">
              EnviroShield rejects opaque black-box AI scores. Every composite rating is an auditable, deterministic sum of physical atmospheric vectors, observed boundary invariants, and peer-reviewed epidemiological damage functions.
            </p>
          </div>

          {/* Trust Metrics Bar */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 pt-2">
            <div className="p-4 rounded bg-[#1d2025] border border-[#272a30] flex flex-col gap-1 shadow-sm">
              <div className="flex items-center justify-between">
                <span className="font-mono text-[10px] text-[#87929a] uppercase font-semibold">Equation Class</span>
                <span className="material-symbols-outlined text-[#8ed5ff] text-[16px]">functions</span>
              </div>
              <span className="font-sans text-[20px] font-bold text-white">Linear Additive</span>
              <span className="font-mono text-[11px] text-[#bdc8d1]">Closed-form deterministic</span>
            </div>

            <div className="p-4 rounded bg-[#1d2025] border border-[#272a30] flex flex-col gap-1 shadow-sm">
              <div className="flex items-center justify-between">
                <span className="font-mono text-[10px] text-[#87929a] uppercase font-semibold">Audit Latency</span>
                <span className="material-symbols-outlined text-[#44e2cd] text-[16px]">speed</span>
              </div>
              <span className="font-mono text-[20px] font-bold text-[#44e2cd]">0.00 ms</span>
              <span className="font-mono text-[11px] text-[#bdc8d1]">Instant physical proof</span>
            </div>

            <div className="p-4 rounded bg-[#1d2025] border border-[#272a30] flex flex-col gap-1 shadow-sm">
              <div className="flex items-center justify-between">
                <span className="font-mono text-[10px] text-[#87929a] uppercase font-semibold">Sensor Verification</span>
                <span className="material-symbols-outlined text-[#8ed5ff] text-[16px]">check_circle</span>
              </div>
              <span className="font-sans text-[20px] font-bold text-white">100% In-Situ</span>
              <span className="font-mono text-[11px] text-[#bdc8d1]">Zero synthetic imputation</span>
            </div>

            <div className="p-4 rounded bg-[#1d2025] border border-[#272a30] flex flex-col gap-1 shadow-sm">
              <div className="flex items-center justify-between">
                <span className="font-mono text-[10px] text-[#87929a] uppercase font-semibold">Cryptographic Trace</span>
                <span className="material-symbols-outlined text-[#a1d2ff] text-[16px]">lock_clock</span>
              </div>
              <span className="font-mono text-[20px] font-bold text-[#8ed5ff]">SHA-256</span>
              <span className="font-mono text-[11px] text-[#bdc8d1]">Continuous Merkle root</span>
            </div>
          </div>
        </div>
      </section>

      {/* Interactive Mathematical Risk Decomposition */}
      <section className="w-full px-4 sm:px-6 lg:px-8 py-8 bg-[#111319]">
        <div className="max-w-6xl mx-auto flex flex-col gap-6">
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
            <div className="flex flex-col gap-1">
              <span className="font-mono text-[10px] font-semibold text-[#8ed5ff] uppercase tracking-wider">
                Mathematical Dissection
              </span>
              <h2 className="font-sans text-[22px] sm:text-[24px] font-bold text-white">
                Additive Physical Risk Formulation
              </h2>
              <p className="font-sans text-[13px] text-[#bdc8d1]">
                Dynamic multi-variate decomposition evaluated for Station <code className="font-mono text-[#44e2cd]">{station.code}</code>.
              </p>
            </div>
            <div className="p-2.5 rounded bg-[#272a30] border border-[#3e484f] flex items-center gap-2 font-mono text-[12px] text-white">
              <span className="text-[#8ed5ff] font-bold">R</span>
              <span>=</span>
              <span>w₁(PM2.5)</span>
              <span>+</span>
              <span>w₂(T, RH)</span>
              <span>+</span>
              <span>w₃(H_inv, u)</span>
            </div>
          </div>

          {/* Equation Flow Cards Bento Grid */}
          <div className="grid grid-cols-1 md:grid-cols-5 gap-3 items-stretch">
            {/* Baseline Card */}
            <div className="p-4 rounded bg-[#1d2025] border border-[#272a30] flex flex-col justify-between shadow-sm hover:bg-[#272a30] transition-colors">
              <div className="flex flex-col gap-1">
                <span className="font-mono text-[10px] text-[#87929a] uppercase font-semibold">Baseline</span>
                <span className="font-sans text-[15px] font-bold text-white">Standard Troposphere</span>
                <span className="font-sans text-[11px] text-[#bdc8d1]">
                  Pristine equilibrium baseline prior to anthropogenic loading
                </span>
              </div>
              <div className="pt-4">
                <div className="flex items-baseline gap-1">
                  <span className="font-mono text-[24px] font-bold text-white">0.0</span>
                  <span className="font-mono text-[11px] text-[#87929a]">pts</span>
                </div>
                <span className="font-mono text-[10px] text-[#44e2cd] uppercase font-semibold">Static Zero Ref</span>
              </div>
            </div>

            {/* Term 1 */}
            <div className="p-4 rounded bg-[#1d2025] border border-[#272a30] flex flex-col justify-between shadow-sm hover:bg-[#272a30] transition-colors">
              <div className="flex flex-col gap-1">
                <div className="flex items-center justify-between">
                  <span className="font-mono text-[10px] text-[#8ed5ff] uppercase font-semibold">Term 01 · 46.6% Weight</span>
                  <span className="material-symbols-outlined text-[#8ed5ff] text-[16px]">blur_on</span>
                </div>
                <span className="font-sans text-[15px] font-bold text-white">Air Quality Impact</span>
                <span className="font-sans text-[11px] text-[#bdc8d1]">
                  PM2.5 Stagnation reading at {station.pm25} µg/m³ against WHO 24h scalar
                </span>
              </div>
              <div className="pt-4 flex flex-col gap-1">
                <div className="flex items-baseline gap-1">
                  <span className="font-mono text-[24px] font-bold text-[#8ed5ff]">+21.4</span>
                  <span className="font-mono text-[11px] text-[#8ed5ff]">pts</span>
                </div>
                <div className="w-full bg-[#0b0e13] h-1.5 rounded overflow-hidden">
                  <div className="bg-[#38bdf8] h-full w-[46.6%]" />
                </div>
              </div>
            </div>

            {/* Term 2 */}
            <div className="p-4 rounded bg-[#1d2025] border border-[#272a30] flex flex-col justify-between shadow-sm hover:bg-[#272a30] transition-colors">
              <div className="flex flex-col gap-1">
                <div className="flex items-center justify-between">
                  <span className="font-mono text-[10px] text-[#44e2cd] uppercase font-semibold">Term 02 · 28.8% Weight</span>
                  <span className="material-symbols-outlined text-[#44e2cd] text-[16px]">thermostat</span>
                </div>
                <span className="font-sans text-[15px] font-bold text-white">Thermal Stress</span>
                <span className="font-sans text-[11px] text-[#bdc8d1]">
                  Heat Index +2.8°C Offset with Vapor Pressure Deficit saturation
                </span>
              </div>
              <div className="pt-4 flex flex-col gap-1">
                <div className="flex items-baseline gap-1">
                  <span className="font-mono text-[24px] font-bold text-[#44e2cd]">+13.2</span>
                  <span className="font-mono text-[11px] text-[#44e2cd]">pts</span>
                </div>
                <div className="w-full bg-[#0b0e13] h-1.5 rounded overflow-hidden">
                  <div className="bg-[#44e2cd] h-full w-[28.8%]" />
                </div>
              </div>
            </div>

            {/* Term 3 */}
            <div className="p-4 rounded bg-[#1d2025] border border-[#272a30] flex flex-col justify-between shadow-sm hover:bg-[#272a30] transition-colors">
              <div className="flex flex-col gap-1">
                <div className="flex items-center justify-between">
                  <span className="font-mono text-[10px] text-[#a1d2ff] uppercase font-semibold">Term 03 · 24.6% Weight</span>
                  <span className="material-symbols-outlined text-[#a1d2ff] text-[16px]">layers</span>
                </div>
                <span className="font-sans text-[15px] font-bold text-white">Boundary Trapping</span>
                <span className="font-sans text-[11px] text-[#bdc8d1]">
                  Inversion ceiling at {station.pblHeight}m trapping boundary layer particulates
                </span>
              </div>
              <div className="pt-4 flex flex-col gap-1">
                <div className="flex items-baseline gap-1">
                  <span className="font-mono text-[24px] font-bold text-[#a1d2ff]">+11.3</span>
                  <span className="font-mono text-[11px] text-[#a1d2ff]">pts</span>
                </div>
                <div className="w-full bg-[#0b0e13] h-1.5 rounded overflow-hidden">
                  <div className="bg-[#a1d2ff] h-full w-[24.6%]" />
                </div>
              </div>
            </div>

            {/* Composite Score Card */}
            <div className="p-4 rounded bg-[#272a30] border border-[#3e484f] flex flex-col justify-between shadow-md">
              <div className="flex flex-col gap-1">
                <div className="flex items-center justify-between">
                  <span className="font-mono text-[10px] text-[#bdc8d1] uppercase font-semibold">Composite Index</span>
                  <span className="w-2 h-2 rounded-full bg-[#44e2cd]" />
                </div>
                <span className="font-sans text-[15px] font-bold text-white">Aggregate Result</span>
                <span className="font-mono text-[11px] text-[#44e2cd] font-semibold">MODERATE RISK CLUSTER</span>
              </div>
              <div className="pt-4 flex flex-col gap-1">
                <div className="flex items-baseline gap-1">
                  <span className="font-sans text-[36px] font-bold text-white leading-none">45.9</span>
                  <span className="font-mono text-[12px] text-[#87929a]">/ 100</span>
                </div>
                <div className="flex items-center gap-1.5">
                  <span className="font-mono text-[10px] text-[#44e2cd] font-bold">VERIFIED BALANCED</span>
                  <span className="material-symbols-outlined text-[#44e2cd] text-[14px]">check</span>
                </div>
              </div>
            </div>
          </div>

          {/* Balance Invariant Verification Bar */}
          <div className="p-3.5 rounded bg-[#0b0e13] border border-[#272a30] flex flex-col sm:flex-row items-center justify-between gap-3 shadow-sm">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded bg-[#1d2025] flex items-center justify-center text-[#44e2cd] border border-[#272a30]">
                <span className="material-symbols-outlined text-[20px]">
                  {balanceAsserted ? 'task_alt' : 'sync'}
                </span>
              </div>
              <div className="flex flex-col">
                <span className="font-mono text-[13px] font-bold text-white">
                  ∑ Terms = 0.0 + 21.4 + 13.2 + 11.3 = 45.9000
                </span>
                <span className="font-mono text-[11px] text-[#bdc8d1]">
                  Deterministic arithmetic invariant satisfied: residual error &lt; 10⁻⁸
                </span>
              </div>
            </div>
            <button
              onClick={handleAssertBalance}
              disabled={verifying}
              type="button"
              className="px-4 py-2 bg-[#1d2025] hover:bg-[#272a30] text-[#8ed5ff] rounded font-mono text-[11px] font-semibold border border-[#272a30] hover:border-[#38bdf8]/50 transition-colors flex items-center gap-1.5 cursor-pointer disabled:opacity-50"
            >
              <span className={`material-symbols-outlined text-[16px] ${verifying ? 'animate-spin' : ''}`}>
                sync
              </span>
              <span>{verifying ? 'Asserting...' : 'Assert Balance Integrity'}</span>
            </button>
          </div>
        </div>
      </section>

      {/* Verified Hardware Sensor Provenance */}
      <section className="w-full px-4 sm:px-6 lg:px-8 py-8 bg-[#0b0e13] border-y border-[#272a30]/50">
        <div className="max-w-6xl mx-auto flex flex-col gap-6">
          <div className="flex flex-col gap-1">
            <div className="flex items-center gap-1.5">
              <span className="material-symbols-outlined text-[#44e2cd] text-[16px]">memory</span>
              <span className="font-mono text-[10px] font-semibold text-[#44e2cd] uppercase">Hardware Trust Architecture</span>
            </div>
            <h2 className="font-sans text-[22px] sm:text-[24px] font-bold text-white">
              Verified Physical Instrument Provenance
            </h2>
            <p className="font-sans text-[13px] text-[#bdc8d1]">
              Traceability records for calibrated in-situ ground arrays feeding the {station.code} matrix.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
            {/* Sensor 1 */}
            <div className="p-4 rounded bg-[#191c21] border border-[#272a30] flex flex-col justify-between shadow-sm hover:border-[#38bdf8]/40 transition-colors">
              <div className="flex flex-col gap-2">
                <div className="flex items-center justify-between">
                  <span className="font-mono text-[10px] text-[#8ed5ff] uppercase font-semibold">Sensor 01 · AEROSOL</span>
                  <span className="px-1.5 py-0.5 rounded bg-[#272a30] text-[#44e2cd] font-mono text-[9px] font-bold border border-[#44e2cd]/30">VALID</span>
                </div>
                <div className="flex flex-col">
                  <span className="font-sans text-[14px] font-bold text-white">Laser Optical Particle Counter</span>
                  <span className="font-mono text-[11px] text-[#87929a]">PM2.5 / PM10 Channels</span>
                </div>
                <div className="flex flex-col gap-1 pt-2 font-mono text-[11px] text-[#bdc8d1] border-t border-[#272a30]">
                  <div className="flex justify-between">
                    <span className="text-[#87929a]">Standard:</span>
                    <span className="text-white">WMO Tier-1</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-[#87929a]">Sensor Drift:</span>
                    <span className="text-[#44e2cd]">&lt; 0.4% / yr</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-[#87929a]">Last Chamber:</span>
                    <span>2025-03-12</span>
                  </div>
                </div>
              </div>

              <div className="pt-3 flex items-center justify-between border-t border-[#272a30]">
                <span className="font-mono text-[10px] text-[#87929a]">SN: OPC-9982-X</span>
                <button
                  type="button"
                  onClick={() => handlePingSensor('s1', 'Laser Optical Counter')}
                  className="text-[#8ed5ff] hover:text-white font-mono text-[11px] font-semibold flex items-center gap-0.5 transition-colors cursor-pointer"
                >
                  <span>{pingedSensors['s1'] ? 'ACK' : 'Ping'}</span>
                  <span className="material-symbols-outlined text-[13px]">arrow_outward</span>
                </button>
              </div>
            </div>

            {/* Sensor 2 */}
            <div className="p-4 rounded bg-[#191c21] border border-[#272a30] flex flex-col justify-between shadow-sm hover:border-[#38bdf8]/40 transition-colors">
              <div className="flex flex-col gap-2">
                <div className="flex items-center justify-between">
                  <span className="font-mono text-[10px] text-[#8ed5ff] uppercase font-semibold">Sensor 02 · KINEMATIC</span>
                  <span className="px-1.5 py-0.5 rounded bg-[#272a30] text-[#44e2cd] font-mono text-[9px] font-bold border border-[#44e2cd]/30">VALID</span>
                </div>
                <div className="flex flex-col">
                  <span className="font-sans text-[14px] font-bold text-white">Sonic 3D Anemometer</span>
                  <span className="font-mono text-[11px] text-[#87929a]">Surface Wind Vectors (u, v, w)</span>
                </div>
                <div className="flex flex-col gap-1 pt-2 font-mono text-[11px] text-[#bdc8d1] border-t border-[#272a30]">
                  <div className="flex justify-between">
                    <span className="text-[#87929a]">Sampling:</span>
                    <span className="text-white">20.0 Hz</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-[#87929a]">Acoustic Drift:</span>
                    <span className="text-[#44e2cd]">±0.01 m/s</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-[#87929a]">Sonic Azimuth:</span>
                    <span>359.8° True</span>
                  </div>
                </div>
              </div>

              <div className="pt-3 flex items-center justify-between border-t border-[#272a30]">
                <span className="font-mono text-[10px] text-[#87929a]">SN: SON-3D-4101</span>
                <button
                  type="button"
                  onClick={() => handlePingSensor('s2', 'Sonic 3D Anemometer')}
                  className="text-[#8ed5ff] hover:text-white font-mono text-[11px] font-semibold flex items-center gap-0.5 transition-colors cursor-pointer"
                >
                  <span>{pingedSensors['s2'] ? 'ACK' : 'Ping'}</span>
                  <span className="material-symbols-outlined text-[13px]">arrow_outward</span>
                </button>
              </div>
            </div>

            {/* Sensor 3 */}
            <div className="p-4 rounded bg-[#191c21] border border-[#272a30] flex flex-col justify-between shadow-sm hover:border-[#38bdf8]/40 transition-colors">
              <div className="flex flex-col gap-2">
                <div className="flex items-center justify-between">
                  <span className="font-mono text-[10px] text-[#8ed5ff] uppercase font-semibold">Sensor 03 · THERMAL</span>
                  <span className="px-1.5 py-0.5 rounded bg-[#272a30] text-[#44e2cd] font-mono text-[9px] font-bold border border-[#44e2cd]/30">VALID</span>
                </div>
                <div className="flex flex-col">
                  <span className="font-sans text-[14px] font-bold text-white">Capacitive Thin-Film Hygrometry</span>
                  <span className="font-mono text-[11px] text-[#87929a]">RH & Vapor Pressure Deficit</span>
                </div>
                <div className="flex flex-col gap-1 pt-2 font-mono text-[11px] text-[#bdc8d1] border-t border-[#272a30]">
                  <div className="flex justify-between">
                    <span className="text-[#87929a]">Calibration:</span>
                    <span className="text-white">NIST Traceable</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-[#87929a]">Accuracy:</span>
                    <span className="text-[#44e2cd]">±0.8% RH</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-[#87929a]">Hysteresis:</span>
                    <span>&lt;0.2%</span>
                  </div>
                </div>
              </div>

              <div className="pt-3 flex items-center justify-between border-t border-[#272a30]">
                <span className="font-mono text-[10px] text-[#87929a]">SN: HYG-NIST-88</span>
                <button
                  type="button"
                  onClick={() => handlePingSensor('s3', 'Capacitive Hygrometer')}
                  className="text-[#8ed5ff] hover:text-white font-mono text-[11px] font-semibold flex items-center gap-0.5 transition-colors cursor-pointer"
                >
                  <span>{pingedSensors['s3'] ? 'ACK' : 'Ping'}</span>
                  <span className="material-symbols-outlined text-[13px]">arrow_outward</span>
                </button>
              </div>
            </div>

            {/* Sensor 4 */}
            <div className="p-4 rounded bg-[#191c21] border border-[#272a30] flex flex-col justify-between shadow-sm hover:border-[#38bdf8]/40 transition-colors">
              <div className="flex flex-col gap-2">
                <div className="flex items-center justify-between">
                  <span className="font-mono text-[10px] text-[#8ed5ff] uppercase font-semibold">Sensor 04 · VERTICAL</span>
                  <span className="px-1.5 py-0.5 rounded bg-[#272a30] text-[#44e2cd] font-mono text-[9px] font-bold border border-[#44e2cd]/30">VALID</span>
                </div>
                <div className="flex flex-col">
                  <span className="font-sans text-[14px] font-bold text-white">Radiosonde Sounding Profile</span>
                  <span className="font-mono text-[11px] text-[#87929a]">PBLH & Inversion Heights</span>
                </div>
                <div className="flex flex-col gap-1 pt-2 font-mono text-[11px] text-[#bdc8d1] border-t border-[#272a30]">
                  <div className="flex justify-between">
                    <span className="text-[#87929a]">Ascent Launch:</span>
                    <span className="text-white">Synoptic 12:00Z</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-[#87929a]">Ceiling Detection:</span>
                    <span className="text-[#44e2cd]">620m AGL</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-[#87929a]">Resolution:</span>
                    <span>0.5 hPa</span>
                  </div>
                </div>
              </div>

              <div className="pt-3 flex items-center justify-between border-t border-[#272a30]">
                <span className="font-mono text-[10px] text-[#87929a]">SN: SND-SYN-0419</span>
                <button
                  type="button"
                  onClick={() => handlePingSensor('s4', 'Radiosonde Sounding')}
                  className="text-[#8ed5ff] hover:text-white font-mono text-[11px] font-semibold flex items-center gap-0.5 transition-colors cursor-pointer"
                >
                  <span>{pingedSensors['s4'] ? 'ACK' : 'Ping'}</span>
                  <span className="material-symbols-outlined text-[13px]">arrow_outward</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Cryptographic End-to-End Ingestion Pipeline (5-Stage Trace) */}
      <section className="w-full px-4 sm:px-6 lg:px-8 py-8 bg-[#111319]">
        <div className="max-w-6xl mx-auto flex flex-col gap-6">
          <div className="flex flex-col gap-1">
            <span className="font-mono text-[10px] font-semibold text-[#8ed5ff] uppercase tracking-wider">
              Cryptographic Audit Chain
            </span>
            <h2 className="font-sans text-[22px] sm:text-[24px] font-bold text-white">
              5-Stage Ingestion & Derivation Provenance
            </h2>
            <p className="font-sans text-[13px] text-[#bdc8d1]">
              Full linear lineage guaranteed by block-hashed atmospheric states with zero probabilistic guesswork.
            </p>
          </div>

          <div className="flex flex-col gap-2 font-mono">
            {/* Stage 01 */}
            <div className="p-3.5 rounded bg-[#1d2025] border border-[#272a30] flex flex-col lg:flex-row lg:items-center justify-between gap-3 hover:bg-[#272a30] transition-colors">
              <div className="flex items-center gap-3">
                <span className="text-[14px] text-[#8ed5ff] font-bold px-2 py-1 rounded bg-[#0b0e13] border border-[#272a30]">
                  01
                </span>
                <div className="flex flex-col font-sans">
                  <span className="text-[14px] font-bold text-white">Telemetry Origin & Observation Ingest</span>
                  <span className="text-[12px] text-[#bdc8d1]">
                    Copernicus Sentinel-5P TROPOMI raster tiles cross-referenced with ground WMO in-situ stations.
                  </span>
                </div>
              </div>
              <div className="flex items-center gap-3 text-[11px]">
                <span className="px-2 py-0.5 rounded bg-[#0b0e13] text-[#87929a] border border-[#272a30]">
                  SHA256: 0x8a91c4...e11d
                </span>
                <span className="text-[#44e2cd] font-bold flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-[#44e2cd]" />
                  VERIFIED
                </span>
              </div>
            </div>

            {/* Stage 02 */}
            <div className="p-3.5 rounded bg-[#1d2025] border border-[#272a30] flex flex-col lg:flex-row lg:items-center justify-between gap-3 hover:bg-[#272a30] transition-colors">
              <div className="flex items-center gap-3">
                <span className="text-[14px] text-[#8ed5ff] font-bold px-2 py-1 rounded bg-[#0b0e13] border border-[#272a30]">
                  02
                </span>
                <div className="flex flex-col font-sans">
                  <span className="text-[14px] font-bold text-white">QA / Outlier Filter & ISO 17025 Conformity</span>
                  <span className="text-[12px] text-[#bdc8d1]">
                    Empirical spike rejection (&gt;3σ Gaussian threshold) and spatial covariance checking across 8 peer nodes.
                  </span>
                </div>
              </div>
              <div className="flex items-center gap-3 text-[11px]">
                <span className="px-2 py-0.5 rounded bg-[#0b0e13] text-[#87929a] border border-[#272a30]">
                  SHA256: 0x3d02e8...77cb
                </span>
                <span className="text-[#44e2cd] font-bold flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-[#44e2cd]" />
                  CONFORMANT
                </span>
              </div>
            </div>

            {/* Stage 03 */}
            <div className="p-3.5 rounded bg-[#1d2025] border border-[#272a30] flex flex-col lg:flex-row lg:items-center justify-between gap-3 hover:bg-[#272a30] transition-colors">
              <div className="flex items-center gap-3">
                <span className="text-[14px] text-[#8ed5ff] font-bold px-2 py-1 rounded bg-[#0b0e13] border border-[#272a30]">
                  03
                </span>
                <div className="flex flex-col font-sans">
                  <span className="text-[14px] font-bold text-white">Physical Transport & Advection Kernels</span>
                  <span className="text-[12px] text-[#bdc8d1]">
                    Conservation-of-mass Navier-Stokes flux computation driven by ECMWF 0.05° high-resolution vector winds.
                  </span>
                </div>
              </div>
              <div className="flex items-center gap-3 text-[11px]">
                <span className="px-2 py-0.5 rounded bg-[#0b0e13] text-[#87929a] border border-[#272a30]">
                  SHA256: 0xfa1107...992a
                </span>
                <span className="text-[#44e2cd] font-bold flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-[#44e2cd]" />
                  CONVERGED
                </span>
              </div>
            </div>

            {/* Stage 04 */}
            <div className="p-3.5 rounded bg-[#1d2025] border border-[#272a30] flex flex-col lg:flex-row lg:items-center justify-between gap-3 hover:bg-[#272a30] transition-colors">
              <div className="flex items-center gap-3">
                <span className="text-[14px] text-[#8ed5ff] font-bold px-2 py-1 rounded bg-[#0b0e13] border border-[#272a30]">
                  04
                </span>
                <div className="flex flex-col font-sans">
                  <span className="text-[14px] font-bold text-white">Risk Synthesis & Epidemiological Normalization</span>
                  <span className="text-[12px] text-[#bdc8d1]">
                    Deterministic scaling against standard clinical dose-response curves and local urban healthcare buffering limits.
                  </span>
                </div>
              </div>
              <div className="flex items-center gap-3 text-[11px]">
                <span className="px-2 py-0.5 rounded bg-[#0b0e13] text-[#87929a] border border-[#272a30]">
                  SHA256: 0x51c4a0...01ea
                </span>
                <span className="text-[#44e2cd] font-bold flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-[#44e2cd]" />
                  NORMALIZED
                </span>
              </div>
            </div>

            {/* Stage 05 */}
            <div className="p-3.5 rounded bg-[#1d2025] border border-[#272a30] flex flex-col lg:flex-row lg:items-center justify-between gap-3 hover:bg-[#272a30] transition-colors">
              <div className="flex items-center gap-3">
                <span className="text-[14px] text-[#8ed5ff] font-bold px-2 py-1 rounded bg-[#0b0e13] border border-[#272a30]">
                  05
                </span>
                <div className="flex flex-col font-sans">
                  <span className="text-[14px] font-bold text-white">Decision Dispatch & Signed Telemetry Feeds</span>
                  <span className="text-[12px] text-[#bdc8d1]">
                    Immediate multicast delivery to underwriter APIs, municipal emergency grids, and sovereign risk desks.
                  </span>
                </div>
              </div>
              <div className="flex items-center gap-3 text-[11px]">
                <span className="px-2 py-0.5 rounded bg-[#0b0e13] text-[#87929a] border border-[#272a30]">
                  SHA256: 0x90be31...ddf0
                </span>
                <span className="text-[#44e2cd] font-bold flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-[#44e2cd]" />
                  BROADCAST
                </span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Visual Analytical Inspection / Rich Visual Block */}
      <section className="w-full px-4 sm:px-6 lg:px-8 py-8 bg-[#0b0e13] border-b border-[#272a30]/50">
        <div className="max-w-6xl mx-auto grid grid-cols-1 lg:grid-cols-3 gap-6 items-center">
          {/* Vector Divergence SVG Box */}
          <div className="p-4 rounded bg-[#191c21] border border-[#272a30] flex flex-col gap-3 shadow-sm">
            <div className="flex items-center justify-between font-mono text-[11px]">
              <span className="text-[#87929a] uppercase font-semibold">Physical Vector Divergence</span>
              <span className="text-[#44e2cd] font-bold">∇ · u = 0</span>
            </div>
            <div className="w-full h-44 bg-[#0b0e13] rounded border border-[#272a30] relative overflow-hidden flex items-center justify-center p-2">
              <svg className="w-full h-full text-[#38bdf8]" fill="none" viewBox="0 0 300 150">
                <path d="M0 30 H300 M0 60 H300 M0 90 H300 M0 120 H300" stroke="currentColor" strokeDasharray="2 4" strokeOpacity="0.1" />
                <path d="M50 0 V150 M100 0 V150 M150 0 V150 M200 0 V150 M250 0 V150" stroke="currentColor" strokeDasharray="2 4" strokeOpacity="0.1" />

                <path d="M0 65 Q75 55 150 70 T300 60" fill="none" stroke="#44e2cd" strokeWidth="1.5" />
                <text x="12" y="58" fill="#44e2cd" className="font-mono text-[9px] font-bold">INVERSION CEILING (620m)</text>

                <path d="M0 110 C50 95, 100 125, 150 105 C200 85, 250 120, 300 100 L300 150 L0 150 Z" fill="#8ed5ff" fillOpacity="0.15" />
                <path d="M0 110 C50 95, 100 125, 150 105 C200 85, 250 120, 300 100" stroke="#8ed5ff" strokeDasharray="4 2" strokeWidth="1.5" />

                <g stroke="#38bdf8" strokeWidth="1.2">
                  <path d="M40 130 H65 M60 127 L65 130 L60 133" />
                  <path d="M120 135 H150 M145 132 L150 135 L145 138" />
                  <path d="M220 130 H245 M240 127 L245 130 L240 133" />
                  <path d="M80 40 H115 M110 37 L115 40 L110 43" />
                  <path d="M180 35 H220 M215 32 L220 35 L215 38" />
                </g>
              </svg>
            </div>
            <div className="flex items-center justify-between font-mono text-[11px] text-[#bdc8d1]">
              <span>Boundary Advection: 1.8 m/s</span>
              <span className="text-[#44e2cd] font-semibold">STABLE STAGNATION</span>
            </div>
          </div>

          {/* Hardware Photo 1 & Photo 2 */}
          <div className="lg:col-span-2 flex flex-col gap-3">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {/* Photo 1 */}
              <div className="h-44 rounded bg-[#1d2025] border border-[#272a30] overflow-hidden relative group">
                <img
                  src="https://lh3.googleusercontent.com/aida-public/AB6AXuDzRCNkEboABIF2k6VLaAUqQ9vzoxXELrIZ_yU2Ia3o1XSdj3D4CZAuMf5ae4OPZDLaTDPzBA82Y3KFvzUPsVp6rxnS5M3u9MEhVutNKdeLxrRI4QavTDn3uwG6mtIDaBFGERAPCUzdR2fTAFMKoG6ViLG_At83uUzIbY_Eq8iJzUcC3TC4NcQwmSzhCM8NCSqrWklggQSFoGkAMgflVAfD5D-rctaA25FOUZ2LlwIUn7egLhURpVHf"
                  alt="Laser optical particle counter instrument array"
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500 opacity-80"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-[#0b0e13] via-[#0b0e13]/40 to-transparent flex flex-col justify-end p-3">
                  <span className="font-mono text-[10px] text-[#44e2cd] uppercase font-bold">Array Node 04A</span>
                  <span className="font-sans text-[13px] text-white font-medium">Laser Optical Sampling Mast</span>
                </div>
              </div>

              {/* Photo 2 */}
              <div className="h-44 rounded bg-[#1d2025] border border-[#272a30] overflow-hidden relative group">
                <img
                  src="https://lh3.googleusercontent.com/aida-public/AB6AXuBvXt9nsa2h7J3UaDZCKJ72W2MSBkvAMVvmR_lmlu7QVe_RL-Ao350qSsusuNjnUeg69TQoTg_H3eB-ipcT1gxjmIuQCkx8Qrq4qN_uiG-mov0fWAZs0k8_PWTlCK9DWN20zECY_qxajMCZvVO2daTcfU8llDxgPsj3GV5dk2tqW3XFfJS46vci4QhufmB5yZizS3NdDhAubuiyQscxgZr8STBTv4DDX4y0mR04ylZwkTEdmLe5Xeog"
                  alt="Scientific 3D sonic anemometer array"
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500 opacity-80"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-[#0b0e13] via-[#0b0e13]/40 to-transparent flex flex-col justify-end p-3">
                  <span className="font-mono text-[10px] text-[#8ed5ff] uppercase font-bold">Array Node 04B</span>
                  <span className="font-sans text-[13px] text-white font-medium">Ultrasonic Wind Vector Profiler</span>
                </div>
              </div>
            </div>

            <div className="p-3 rounded bg-[#191c21] border border-[#272a30] flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="material-symbols-outlined text-[#8ed5ff] text-[18px]">verified</span>
                <span className="font-sans text-[12px] text-white">
                  Calibration certificate on file with WMO Central Calibration Laboratory (CCL).
                </span>
              </div>
              <button
                type="button"
                onClick={onOpenCalibration}
                className="font-mono text-[11px] text-[#8ed5ff] hover:text-white uppercase transition-colors cursor-pointer"
              >
                View ISO 17025 Cert
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* Scientific Analyst Executive Brief & Verification Dispatch */}
      <section className="w-full px-4 sm:px-6 lg:px-8 py-8 bg-[#111319]">
        <div className="max-w-6xl mx-auto flex flex-col gap-6">
          <div className="p-5 sm:p-6 rounded bg-[#191c21] border border-[#272a30] shadow-xl flex flex-col gap-6">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-3 bg-[#272a30]/60 px-4 py-2.5 rounded border border-[#272a30] gap-3">
              <div className="flex items-center gap-2.5">
                <span className="material-symbols-outlined text-[#44e2cd] text-[20px]">policy</span>
                <div className="flex flex-col">
                  <span className="font-sans text-[15px] font-bold text-white">
                    Scientific Analyst Executive Verification Dispatch
                  </span>
                  <span className="font-mono text-[11px] text-[#bdc8d1]">
                    DISPATCH_ID: ES-EXEC-2025-0518-0912Z
                  </span>
                </div>
              </div>
              <div className="flex items-center gap-1.5 font-mono text-[11px] text-[#44e2cd] bg-[#0b0e13] px-2.5 py-1 rounded border border-[#272a30]">
                <span className="material-symbols-outlined text-[14px]">lock</span>
                <span>SIGNED BY CORE-A1</span>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="md:col-span-2 flex flex-col gap-4">
                <div className="flex flex-col gap-1.5">
                  <span className="font-mono text-[10px] text-[#87929a] uppercase font-semibold">Executive Synthesis</span>
                  <p className="font-sans text-[13px] text-white leading-relaxed">
                    The prevailing composite risk rating of <strong className="text-[#44e2cd] font-mono font-bold">45.9 / 100</strong> represents an atmospheric entrapment regime governed primarily by low boundary-layer advection (<code className="text-[#8ed5ff] font-mono">u_10m = 1.4 m/s</code>) combined with an early morning nocturnal subsidence inversion at <code className="text-[#8ed5ff] font-mono">620m AGL</code>.
                  </p>
                  <p className="font-sans text-[13px] text-[#bdc8d1] leading-relaxed">
                    Fine particulate mass density (<code className="text-white font-mono">PM2.5 = 86.4 µg/m³</code>) contributes 46.6% to the aggregate rating. Thermal-humidity stress provides an incremental 28.8% push via vapor pressure deficit suppression. All inputs are verifiable down to raw voltage pulses recorded on physical ground sensors with complete SHA-256 traceability.
                  </p>
                </div>

                {/* Risk Implications */}
                <div className="p-3.5 rounded bg-[#1d2025] border border-[#272a30] flex flex-col gap-1.5">
                  <span className="font-mono text-[10px] text-[#8ed5ff] uppercase font-bold">
                    Institutional Risk Implications
                  </span>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-1 font-mono text-[11px] text-[#bdc8d1]">
                    <div className="flex items-center gap-1.5">
                      <span className="text-[#44e2cd]">▸</span>
                      <span>Industrial Ventilation: RESTRICT TO MIN</span>
                    </div>
                    <div className="flex items-center gap-1.5">
                      <span className="text-[#44e2cd]">▸</span>
                      <span>Underwriting Stagnation Exposure: MODERATE</span>
                    </div>
                    <div className="flex items-center gap-1.5">
                      <span className="text-[#44e2cd]">▸</span>
                      <span>Civic Transport Regulation: ADVISORY STAGE 1</span>
                    </div>
                    <div className="flex items-center gap-1.5">
                      <span className="text-[#44e2cd]">▸</span>
                      <span>Hospital Surge Buffer: NOMINAL</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Cryptographic Seal */}
              <div className="p-4 rounded bg-[#1d2025] border border-[#272a30] flex flex-col justify-between shadow-sm">
                <div className="flex flex-col gap-2">
                  <span className="font-mono text-[10px] text-[#87929a] uppercase font-semibold">Cryptographic Stamp</span>
                  <div className="flex items-center gap-1 text-[#44e2cd] font-mono text-[11px] font-bold">
                    <span className="material-symbols-outlined text-[16px]">verified</span>
                    <span>Deterministic Signature Valid</span>
                  </div>
                  <div className="p-2 rounded bg-[#0b0e13] font-mono text-[11px] text-[#bdc8d1] break-all border border-[#272a30]">
                    DIGEST: 0x9f82b41298ca4150de299cf762eab8012fca128a
                  </div>
                  <div className="flex flex-col gap-0.5 font-mono text-[10px] text-[#87929a] pt-1">
                    <span>TIMESTAMP: 2025-05-18 14:42:01 UTC</span>
                    <span>ALGORITHM: ED25519 / SHA256</span>
                    <span>KEY_ID: PUB_ENVIRO_CORE_01</span>
                  </div>
                </div>

                <div className="pt-4 flex flex-col gap-1.5">
                  <button
                    onClick={handleCopyProof}
                    type="button"
                    className="w-full py-2 bg-[#38bdf8] text-[#004965] hover:bg-[#8ed5ff] transition-colors rounded font-mono text-[11px] font-bold text-center shadow cursor-pointer"
                  >
                    Copy Full Block Proof
                  </button>
                  <span className="text-center font-mono text-[9px] text-[#87929a] uppercase font-semibold">
                    Zero Hallucination Guaranteed
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};
